---
- name: copy script
  copy:
    src: "git-credential-helper-env.sh"
    dest: "/usr/local/bin/git-credential-helper-env.sh"
    mode: "u=rwx,go=rx"

- name: configure script
  git_config:
    name: "credential.helper"
    value: "env"
    scope: "{{ git_credential_scope }}"
    repo: "{{ git_credential_repo_path }}"
  become: "{{ git_credential_config_user }}"
